openapi: 3.0.0
info:
  title: Trello REST API
  version: 0.0.1
  description: >-
    This document contains information about how to authenticate with the Trello
    API.
servers:
  - url: 'https://api.trello.com/1'
components:
  securitySchemes:
    APIKey:
      type: apiKey
      in: query
      name: key
    APIToken:
      in: query
      name: token
      type: apiKey
  schemas: {}
security:
  - APIKey: []
    APIToken: []
paths:
  '/boards/{id}/cards':
    get:
      description: >-
        Get all of the open Cards on a Board. See [Nested
        Resources](/cloud/trello/guides/rest-api/nested-resources/) for more
        information.
      parameters:
        - id
        - limit
        - before
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
              examples:
                sample:
                  summary: Example response
                  value:
                    - id: "card_id_123"
                      badges:
                        attachments: 0
                        fogbugz: ""
                        checkItems: 0
                        checkItemsChecked: 0
                        checkItemsEarliestDue: null
                        comments: 0
                        description: false
                        due: null
                        dueComplete: false
                        lastUpdatedByAi: false
                        start: null
                        externalSource: null
                        attachmentsByType:
                          trello:
                            board: 0
                            card: 0
                        location: false
                        votes: 0
                        maliciousAttachments: 0
                        viewingMemberVoted: false
                        subscribed: false
                      checkItemStates: []
                      closed: false
                      dueComplete: false
                      dateLastActivity: "2025-06-06T06:08:05.912Z"
                      desc: ""
                      descData:
                        emoji: {}
                      due: null
                      dueReminder: null
                      email: null
                      idBoard: "board_id_456"
                      idChecklists: []
                      idList: "list_id_789"
                      idMembers: []
                      idMembersVoted: []
                      idShort: 1
                      idAttachmentCover: null
                      labels: []
                      idLabels: []
                      manualCoverAttachment: false
                      name: "Card Name"
                      nodeId: "node_id_abc"
                      pinned: false
                      pos: 140737488355328
                      shortLink: "short_link_xyz"
                      shortUrl: "https://trello.com/c/short_link_xyz"
                      start: null
                      subscribed: false
                      url: "https://trello.com/c/short_link_xyz/1-card-name"
                      cover:
                        idAttachment: null
                        color: null
                        idUploadedBackground: null
                        size: "normal"
                        brightness: "dark"
                        idPlugin: null
                      isTemplate: false
                      cardRole: null
                      mirrorSourceId: null
  '/members/{id}':
    get:
      description: Get a member
      parameters:
        - id
        - actions
        - boards
        - boardBackgrounds
        - boardsInvited
        - boardsInvited_fields
        - boardStars
        - cards
        - customBoardBackgrounds
        - customEmoji
        - customStickers
        - fields
        - notifications
        - organizations
        - organization_fields
        - organization_paid_account
        - organizationsInvited
        - organizationsInvited_fields
        - paid_account
        - savedSearches
        - tokens
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Member'
  '/members/{id}/boards':
    get:
      description: Lists the boards that the user is a member of.
      parameters:
        - id
        - filter
        - fields
        - lists
        - organization
        - organization_fields
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
              examples:
                sample:
                  summary: Example response
                  value:
                    - id: "exampleBoardId"
                      nodeId: "ari:cloud:trello::board/workspace/exampleOrgId/exampleBoardId"
                      name: "Example Board Name"
                      desc: ""
                      descData: null
                      closed: false
                      dateClosed: null
                      idOrganization: "exampleOrgId"
                      idEnterprise: null
                      pinned: false
                      starred: false
                      url: "https://trello.com/b/exampleShortLink/example-board-name"
                      shortLink: "exampleShortLink"
                      subscribed: false
                      labelNames:
                        green: ""
                        yellow: ""
                        orange: ""
                      powerUps: []
                      dateLastActivity: "2025-03-26T12:04:13.067Z"
                      dateLastView: "2025-06-06T06:07:13.134Z"
                      shortUrl: "https://trello.com/b/exampleShortLink"
                      idTags: []
                      datePluginDisable: null
                      creationMethod: null
                      ixUpdate: "1"
                      templateGallery: null
                      enterpriseOwned: false
                      idBoardSource: null
                      premiumFeatures:
                        - "additionalBoardBackgrounds"
                        - "additionalStickers"
                        - "customBoardBackgrounds"
                        - "customEmoji"
                        - "customStickers"
                        - "plugins"
                      idMemberCreator: "exampleMemberId"
                      type: null
                      memberships:
                        - id: "exampleMembershipId"
                          idMember: "exampleMemberId"
                          memberType: "admin"
                          unconfirmed: false
                          deactivated: false
  '/organizations/{id}/members':
    get:
      description: List the members in a Workspace
      parameters:
        - id
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/Member'
              examples:
                sample:
                  summary: Example response
                  value:
                    - id: "examplesaasID1"
                      fullName: "My full name"
                      username: "examplesaas1"
                      lastActive: "2025-04-06T08:37:21.065Z"
  '/cards/{id}/attachments':
    get:
      description: List the attachments on a card
      parameters:
        - name: id
          in: path
          description: The ID of the Card
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: All or a comma-separated list of attachment fields
          required: false
          schema:
            type: string
            default: all
        - name: filter
          in: query
          description: Use cover to restrict to just the cover attachment
          required: false
          schema:
            type: string
            default: "false"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attachment'
              examples:
                sample:
                  summary: Example response
                  value:
                    - id: "5abbe4b7ddc1b351ef961414"
                      bytes: "<string>"
                      date: "2018-10-17T19:10:14.808Z"
                      edgeColor: "yellow"
                      idMember: "5abbe4b7ddc1b351ef961414"
                      isUpload: false
                      mimeType: ""
                      name: "Deprecation Extension Notice"
                      previews: []
                      url: "https://admin.typeform.com/form/RzExEM/share#/link"
                      pos: 1638
